package org.ecsail.mvci.membership.mvci.person;

public enum PersonMessage {
    INSERT_AWARD, UPDATE_AWARD, DELETE_AWARD, UPDATE_PHONE, DELETE_PHONE, SAVE_IMAGE, INSERT_PHONE, INSERT_EMAIL, DELETE_EMAIL, UPDATE_EMAIL, INSERT_POSITION, UPDATE_POSITION, DELETE_OFFICER, DELETE_POSITION;
}
