package org.ecsail.mvci.main;

public enum MainMessage {
    GET_POSITIONS,
    CLOSE_ALL_CONNECTIONS,
    CLOSE_ALL_CONNECTIONS_AND_EXIT,
    CREATE_CONNECT_CONTROLLER,
    BACKUP_DATABASE,
    PRIMARY_STAGE_COMPLETE,
    SELECT_TAB,
    SHOW_LOG,
    STOP_SPINNER,
    SET_CONNECT_ERROR_FALSE,
    SET_CONNECT_ERROR_TRUE,
    FETCH_DIRECTORY, FAIL, SUCCESS, NONE
}
