package org.ecsail.mvci_boat;

public enum BoatMessage {
    DELETE_OWNER,
    DELETE_NOTE,
    DELETE_IMAGE,
    DELETE_BOAT,
    UPDATE_NOTE,
    UPDATE_BOAT,
    SET_DEFAULT,
    INSERT_IMAGE,
    INSERT_NOTE,
    INSERT_OWNER,
    OWNER_DIALOGUE,
    MOVE_FORWARD,
    MOVE_BACKWARD,
    INFORM,
    GET_MEMBERSHIP,
    DOWNLOAD_IMAGE
}
