package org.ecsail.mvci_connect;

public enum ConnectMessage {
    SAVE_LOGINS,
    SUPPLY_LOGINS,
    COPY_CURRENT_TO_MATCHING, PRINT_LOGIN_OBJECTS, CLEAR_DEFAULT_FROM_ALL_LOGIN_OBJECTS, SET_CURRENT_LOGIN_AS_DEFAULT, UPDATE_CURRENT_LOGIN, UPDATE_COMBO_BOX, CREATE_NEW_LOGIN, CONNECT_TO_SERVER
}
